"use client";

import { ArrowRight, CaretDown, Play, Sparkle, SpeakerSlash } from "@phosphor-icons/react";
import { useEffect, useMemo, useRef, useState } from "react";

import { Dialog, DialogContent, DialogTitle } from "@/components/ui/dialog";
import type { TemplateCandidate } from "@/lib/agent/events";
import { formatCredits, renderCost } from "@/lib/credits/prices";

/**
 * Choosing a format.
 *
 * Two different things are on this screen and they must not look the same. A few
 * formats have been *recommended* — scored against the brand, then argued for in
 * a sentence written about this business — and the rest of the library is merely
 * *available*. Back when the whole library fitted on one rail those were the
 * same list, and the line above it said "these fit the brief" about all of them,
 * which was a claim it could not support.
 *
 * So the recommendation is portraits with the reason set underneath, at the size
 * and shape the finished thing will be, because what is being chosen is a video.
 * The rest is a disclosure below: rows, hairlines, a fit bar — the register of a
 * catalogue rather than a pitch. Browsing is scanning and choosing is judging,
 * and they get different typography.
 *
 * Each card plays an example the template made of itself — a real render of that
 * graph against a fixture brand, generated by `npm run previews`. It plays on
 * hover, because three cards playing at once is a fruit machine, and with sound
 * and controls in the dialog, where looking at it properly is the only reason
 * you opened it.
 *
 * A template with no example yet says so. That is not a gap to paper over with
 * an illustration: the question the card answers is "what does this format
 * produce", and the only thing that answers it is footage this format produced.
 */

/** Same inks as the marketing gallery, so the two surfaces stay one family. */
const TONES = ["#d4552b", "#128f96", "#2b2a55", "#3f8a5e", "#6f56b5", "#c01f3f"];

/**
 * Colours for one shelf.
 *
 * Hashing each id independently is the obvious approach and it is wrong here:
 * two of the shipped templates collide, and a row where two of three cards are
 * the same teal looks like a rendering bug rather than a palette. So the first
 * id picks a starting point and the rest of the row walks on from there —
 * stable for a given set, and never two the same until there are more templates
 * than colours.
 */
const tonesFor = (ids: string[]) => {
  const start = [...(ids[0] ?? "")].reduce((sum, char) => sum + char.charCodeAt(0), 0);

  return new Map(
    ids.map((id, index) => [id, TONES[(start + index) % TONES.length]])
  );
};

const Clip = ({
  src,
  poster,
  playing,
}: {
  src: string;
  poster?: string;
  playing: boolean;
}) => {
  const video = useRef<HTMLVideoElement>(null);

  /**
   * Whether the picture is actually moving, as opposed to whether we have asked
   * it to.
   *
   * These are not the same moment. `preload="metadata"` means the first hover
   * fetches the rest of the file, so playback begins about a second after the
   * pointer arrives — and a play mark that vanished on the ask left a second of
   * a still frame pretending to be a playing one.
   */
  const [rolling, setRolling] = useState(false);

  // `autoPlay` only fires at load, so the hover has to drive playback directly.
  // Rewound on the way out, or a second hover resumes mid-clip and the card
  // shows a beat that makes no sense on its own.
  useEffect(() => {
    const element = video.current;
    if (!element) return;

    if (playing) {
      void element.play().catch(() => {});
    } else {
      element.pause();
      element.currentTime = 0;
    }
  }, [playing]);

  return (
    <>
      <video
        ref={video}
        src={src}
        poster={poster}
        // Muted and looping: this is a thumbnail that moves, not a player. The
        // copy in the dialog has sound and controls.
        muted
        loop
        playsInline
        preload="metadata"
        onPlaying={() => setRolling(true)}
        onPause={() => setRolling(false)}
        className="absolute inset-0 size-full object-cover"
      />

      {/* Out of the way once the clip is running, and pulsing while it is being
          fetched — the wait is short but it is not nothing. */}
      <span
        aria-hidden
        className={`absolute left-1/2 top-1/2 grid size-11 -translate-x-1/2 -translate-y-1/2 place-items-center rounded-full bg-white/85 text-graphite transition-all duration-300 ease-[var(--ease-out)] ${
          rolling ? "scale-90 opacity-0" : "opacity-100 group-hover:scale-110"
        } ${playing && !rolling ? "pending" : ""}`}
      >
        <Play weight="fill" className="ml-0.5 size-3.5" />
      </span>
    </>
  );
};

/** The card face: the example if there is one, otherwise an honest blank. */
const Frame = ({
  template,
  tone,
  playing,
}: {
  template: TemplateCandidate;
  tone: string;
  playing: boolean;
}) => {
  if (template.preview) {
    return <Clip src={template.preview} poster={template.still} playing={playing} />;
  }

  /**
   * Tinted paper, not poster paint.
   *
   * There was one of these on screen at a time when three formats shipped and
   * two of them had examples. With eleven formats, most of a recommendation is
   * blank plates, and at full saturation three of them side by side read as a
   * colour chart — loud enough to outrank the badge, the reasons and the actual
   * footage on the cards that do have an example. So the tone is mixed into the
   * paper and spent on the label, which leaves saturation to mean "this is a
   * real frame".
   */
  return (
    <>
      <span
        aria-hidden
        className="absolute inset-0"
        style={{ backgroundColor: `color-mix(in oklab, ${tone} 16%, var(--paper-sunk))` }}
      />
      <span
        className="absolute inset-x-3 top-1/2 -translate-y-1/2 text-center font-mono text-[10px] uppercase leading-relaxed tracking-[0.12em]"
        style={{ color: tone }}
      >
        No example
        <br />
        rendered yet
      </span>
    </>
  );
};

/**
 * How close this is to the best match, drawn rather than stated.
 *
 * Only in the browse list, and deliberately not on the recommended cards: a
 * recommendation already carries its argument in words, and a number sitting
 * beside a sentence invites somebody to trust the number instead. Down here,
 * where eight formats are scanned at once, comparison is the whole point.
 */
const Fit = ({ value }: { value: number }) => (
  <span
    className="flex shrink-0 items-center gap-2"
    title={`${value}% of the best match`}
  >
    <span aria-hidden className="h-1 w-10 overflow-hidden rounded-full bg-rule">
      <span
        className="block h-full rounded-full bg-graphite/45 transition-[width] duration-500 ease-[var(--ease-out)]"
        style={{ width: `${Math.max(4, Math.min(value, 100))}%` }}
      />
    </span>
    <span className="w-6 text-right font-mono text-[10px] tabular-nums text-mute">
      {value}
    </span>
  </span>
);

export default function TemplateCards({
  items,
  library = [],
  prompt,
  chosen,
  disabled,
  onChoose,
}: {
  /** The recommendation: a few formats, each with a reason of its own. */
  items: TemplateCandidate[];
  /** Everything else the library holds, ranked but not argued for. */
  library?: TemplateCandidate[];
  prompt?: string;
  chosen?: string;
  disabled?: boolean;
  onChoose: (template: TemplateCandidate) => void;
}) {
  const [open, setOpen] = useState<TemplateCandidate | null>(null);
  const [lit, setLit] = useState<string | null>(null);
  const [browsing, setBrowsing] = useState(false);

  const tones = useMemo(
    () => tonesFor([...items, ...library].map((template) => template.id)),
    [items, library]
  );

  const total = items.length + library.length;

  return (
    <div className="stream">
      <div className="flex items-baseline justify-between gap-3">
        <p className="font-mono text-[11px] uppercase tracking-[0.14em] text-mute">
          {prompt ?? "Picked for this brand"}
        </p>
        {/* Says out loud that a choice was made on their behalf, and how big the
            field was. Three of eleven is a recommendation; three of three is a
            menu, and calling that a recommendation would be a lie the moment
            somebody counted. */}
        {library.length ? (
          <p className="shrink-0 font-mono text-[11px] tabular-nums text-mute">
            {items.length} of {total}
          </p>
        ) : null}
      </div>

      <ul className="-mx-1 mt-3 flex snap-x snap-mandatory gap-3 overflow-x-auto px-1 pb-2 sm:grid sm:grid-cols-3 sm:overflow-visible">
        {items.map((template, index) => {
          const picked = chosen === template.id;
          const passed = Boolean(chosen) && !picked;
          const tone = tones.get(template.id) ?? TONES[0];

          return (
            <li
              key={template.id}
              style={{ "--i": index } as React.CSSProperties}
              className={`card-in w-[47%] shrink-0 snap-start sm:w-auto ${
                passed ? "shelved" : ""
              }`}
            >
              <button
                type="button"
                onClick={() => setOpen(template)}
                onMouseEnter={() => setLit(template.id)}
                onMouseLeave={() =>
                  setLit((current) => (current === template.id ? null : current))
                }
                onFocus={() => setLit(template.id)}
                onBlur={() =>
                  setLit((current) => (current === template.id ? null : current))
                }
                className="group w-full text-left outline-none"
                aria-label={`Preview ${template.name}`}
              >
                <div
                  className={`relative aspect-[9/16] overflow-hidden rounded-xl border transition-all duration-300 ease-[var(--ease-out)] group-hover:-translate-y-1 group-focus-visible:ring-2 group-focus-visible:ring-graphite group-focus-visible:ring-offset-2 group-focus-visible:ring-offset-paper ${
                    picked
                      ? "border-graphite ring-2 ring-graphite"
                      : "border-black/10 group-hover:shadow-[0_12px_28px_-14px_rgba(12,10,9,0.5)]"
                  }`}
                >
                  <Frame
                    template={template}
                    tone={tone}
                    playing={lit === template.id}
                  />

                  <span className="absolute left-2 top-2 flex items-center gap-1 rounded-md bg-black/40 px-1.5 py-0.5 font-mono text-[10px] tabular-nums text-white">
                    {template.durationRange[0]}–{template.durationRange[1]}s
                    {/* A muted example needs to say so where it plays, not only
                        in the dialog — the shelf is where most people will watch
                        it, and silence with no explanation reads as broken. */}
                    {template.preview && template.previewSilent ? (
                      <SpeakerSlash weight="fill" aria-label="Silent draft" className="size-2.5" />
                    ) : null}
                  </span>

                  {/* "Top pick", not "best fit". They are different claims and
                      the wrong one is checkable: the order here is the agent's
                      judgement about the business, and the highest tag score is
                      often a format it passed over. One badge, on one card, and
                      gone as soon as a choice exists — at that point the only
                      card worth pointing at is the one being made. */}
                  {index === 0 && !chosen ? (
                    <span className="absolute right-2 top-2 flex items-center gap-1 rounded-md bg-ember px-1.5 py-0.5 font-mono text-[10px] uppercase tracking-[0.1em] text-white">
                      <Sparkle weight="fill" aria-hidden className="size-2.5" />
                      Top pick
                    </span>
                  ) : null}

                  {picked ? (
                    <span className="absolute inset-x-0 bottom-0 bg-graphite py-1 text-center font-mono text-[10px] uppercase tracking-[0.14em] text-white">
                      Making
                    </span>
                  ) : null}
                </div>

                <p className="mt-2 flex items-baseline justify-between gap-2">
                  <span className="truncate text-sm font-medium text-graphite">
                    {template.name}
                  </span>
                  <span className="shrink-0 font-mono text-[10px] tabular-nums text-mute">
                    {formatCredits(renderCost(template))}
                  </span>
                </p>
                {template.concept ? (
                  <p className="truncate text-xs text-mute">{template.concept}</p>
                ) : null}
                {/* The reason, in the agent's own words, about this business.
                    It is the entire difference between a ranked list and a
                    recommendation, so it gets room on the card rather than
                    being hidden behind a click. */}
                {template.why ? (
                  <p className="pretty mt-1.5 text-xs leading-snug text-mute">
                    {template.why}
                  </p>
                ) : null}
              </button>
            </li>
          );
        })}
      </ul>

      {library.length ? (
        <div className="mt-1">
          <button
            type="button"
            onClick={() => setBrowsing((current) => !current)}
            aria-expanded={browsing}
            className="flex items-center gap-1.5 rounded-md py-1 text-xs text-mute transition-colors duration-150 hover:text-graphite focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-graphite"
          >
            <CaretDown
              weight="bold"
              aria-hidden
              className={`size-3 transition-transform duration-300 ease-[var(--ease-out)] ${
                browsing ? "rotate-180" : ""
              }`}
            />
            {browsing
              ? "Hide the rest of the library"
              : `Browse the other ${library.length} format${
                  library.length === 1 ? "" : "s"
                }`}
          </button>

          <div className="unfurl" data-open={browsing}>
            <div>
              {/* Present but unreachable while closed. The rows are clipped to
                  zero height, and a tab stop inside a box nobody can see is the
                  classic way a disclosure breaks a keyboard. */}
              <ul inert={!browsing} className="mt-1 border-t border-rule">
                {library.map((template) => {
                  const picked = chosen === template.id;

                  return (
                    <li key={template.id} className="border-b border-rule">
                      <button
                        type="button"
                        onClick={() => setOpen(template)}
                        className={`flex w-full items-center gap-3 px-1 py-2.5 text-left transition-colors duration-150 hover:bg-paper-sunk/60 focus-visible:outline-2 focus-visible:-outline-offset-2 focus-visible:outline-graphite ${
                          !picked && chosen ? "shelved" : ""
                        }`}
                        aria-label={`Preview ${template.name}`}
                      >
                        <span className="min-w-0 flex-1">
                          <span className="block truncate text-sm text-graphite">
                            {template.name}
                            {picked ? (
                              <span className="ml-2 font-mono text-[10px] uppercase tracking-[0.14em] text-ember">
                                Making
                              </span>
                            ) : null}
                          </span>
                          {/* The first sentence of the description, which is
                              written to be exactly this: what the format does,
                              before the paragraph explains how. */}
                          <span className="block truncate text-xs text-mute">
                            {template.durationRange[0]}–{template.durationRange[1]}s ·{" "}
                            {template.description.split(/(?<=\.)\s/)[0]}
                          </span>
                        </span>
                        {template.fit !== undefined ? <Fit value={template.fit} /> : null}
                      </button>
                    </li>
                  );
                })}
              </ul>
            </div>
          </div>
        </div>
      ) : null}

      <Dialog open={Boolean(open)} onOpenChange={(next) => !next && setOpen(null)}>
        <DialogContent className="border-rule bg-paper-lift p-0 sm:max-w-md">
          {open ? (
            <div className="grid gap-4 p-5 sm:grid-cols-[150px_minmax(0,1fr)]">
              <div className="relative aspect-[9/16] overflow-hidden rounded-xl border border-black/10">
                {open.preview ? (
                  <video
                    src={open.preview}
                    poster={open.still}
                    controls
                    autoPlay
                    loop
                    playsInline
                    className="size-full object-cover"
                  />
                ) : (
                  <Frame
                    template={open}
                    tone={tones.get(open.id) ?? TONES[0]}
                    playing={false}
                  />
                )}
              </div>

              <div className="flex flex-col">
                <DialogTitle className="text-base font-semibold text-graphite">
                  {open.name}
                </DialogTitle>

                {open.concept ? (
                  <p className="pretty mt-2 text-sm leading-relaxed text-graphite">
                    {open.concept}
                  </p>
                ) : null}

                {open.why ? (
                  <p className="pretty mt-2 text-sm leading-relaxed text-mute">
                    {open.why}
                  </p>
                ) : (
                  <p className="pretty mt-2 text-sm leading-relaxed text-mute">
                    {open.description}
                  </p>
                )}

                {/* The price sits with the shape, in the same mono figures, at
                    the moment somebody is deciding whether to spend it. Quoted
                    from the same function that does the charging, so the number
                    on this line is the number that comes off the balance. */}
                <p className="mt-3 font-mono text-[10px] tracking-[0.06em] text-mute">
                  {open.aspect} · {open.durationRange[0]}–{open.durationRange[1]}s ·{" "}
                  <span className="text-graphite">
                    {formatCredits(renderCost(open))} credits
                  </span>
                </p>

                {/* Said plainly, because it changes what the panel beside it is
                    worth: an example is this graph's own output, and its absence
                    is not a loading state. The silence is worth naming too — it
                    belongs to the draft backend, not to the format, and somebody
                    judging a talking-head format on a muted clip is judging the
                    wrong thing. */}
                <p className="pretty mt-1 text-xs leading-relaxed text-mute">
                  {open.preview
                    ? open.previewSilent
                      ? "The example is this template, run on a sample brand — a silent draft. Your render speaks."
                      : "The example is this template, run on a sample brand."
                    : "No example has been rendered for this one yet."}
                </p>

                <button
                  type="button"
                  disabled={disabled}
                  onClick={() => {
                    onChoose(open);
                    setOpen(null);
                  }}
                  className="mt-auto flex items-center justify-center gap-2 rounded-full bg-graphite px-4 py-2.5 text-sm font-medium text-white transition-all duration-200 ease-[var(--ease-out)] hover:bg-graphite/85 active:scale-[0.98] focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-graphite disabled:opacity-40"
                >
                  Make this one
                  <ArrowRight weight="bold" aria-hidden className="size-4" />
                </button>
              </div>
            </div>
          ) : null}
        </DialogContent>
      </Dialog>
    </div>
  );
}
